#!/usr/bin/env bash
# B-002: Regression Testing
# SC-8: Key workflows produce same artifacts under CC-native plugin install
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "=== Workflow 1: spec CREATE ==="
echo "Baseline (CC-native plugin-dir):"
echo "  1. Load via: claude --plugin-dir $REPO_ROOT/plugins/ac-workflow"
echo "  2. Run: /spec CREATE specs/2026/02/test/000-regression-test.md"
echo "  3. Record: exit code, created files, file content structure"
echo ""
echo "Plugin install (marketplace):"
echo "  1. Install: claude plugin install ac-workflow@agentic-plugins"
echo "  2. Run same: /spec CREATE specs/2026/02/test/000-regression-test.md"
echo "  3. Compare: exit code, created files, file content structure"
echo ""
echo "Pass criteria: Same file created, same section structure, no path errors"
echo ""

echo "=== Workflow 2: mux-ospec ==="
echo "Baseline (CC-native plugin-dir):"
echo "  1. Load via: claude --plugin-dir $REPO_ROOT/plugins/ac-workflow"
echo "  2. Run: /mux-ospec <existing-spec>"
echo "  3. Record: exit code, output format"
echo ""
echo "Plugin install (marketplace):"
echo "  1. Install: claude plugin install ac-workflow@agentic-plugins"
echo "  2. Run same mux-ospec skill"
echo "  3. Compare output"
echo ""
echo "Pass criteria: Same output format, no path-resolution errors"
echo ""

echo "=== Workflow 3: pull-request ==="
echo "Baseline (CC-native plugin-dir):"
echo "  1. Load via: claude --plugin-dir $REPO_ROOT/plugins/ac-git"
echo "  2. Run: /pull-request (on a branch with changes)"
echo "  3. Record: exit code, PR created/output"
echo ""
echo "Plugin install (marketplace):"
echo "  1. Install: claude plugin install ac-git@agentic-plugins"
echo "  2. Run same pull-request skill"
echo "  3. Compare output"
echo ""
echo "Pass criteria: Same behavior, no missing file errors"
echo ""

echo "=== Path resolution verification ==="
echo "Key paths that must resolve under plugin install:"
echo "  - Spec agents: \${CLAUDE_PLUGIN_ROOT}/agents/ (ac-workflow)"
echo "  - Spec resolver: \${CLAUDE_PLUGIN_ROOT}/scripts/spec-resolver.sh (ac-workflow)"
echo "  - Hook scripts: \${CLAUDE_PLUGIN_ROOT}/scripts/hooks/ (ac-git, ac-tools)"
echo ""
echo "All paths resolve via \${CLAUDE_PLUGIN_ROOT} -- no external dependencies."
echo ""

echo "=== PASS/FAIL checklist ==="
echo "[ ] spec CREATE -- same file artifacts, no path errors (plugin-dir + install)"
echo "[ ] mux-ospec -- same output, no path errors (plugin-dir + install)"
echo "[ ] pull-request -- same behavior, no path errors (plugin-dir + install)"
echo "[ ] All paths resolve via CLAUDE_PLUGIN_ROOT -- no AGENTIC_GLOBAL fallback"
